# Generated by Django 3.2.7 on 2021-10-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_auto_20211004_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
    ]
